"""
scripts/populate_ui_test_seed_jobs.py
Populates high-quality UI test/seed recruitment data across 12 categories and various departments.
Strictly marks all evidence texts with "[UI용 테스트/시드]".
"""

import json
import os
import hashlib
from datetime import datetime

WORKSPACE_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
INTEL_PATHS = [
    os.path.join(WORKSPACE_ROOT, "data", "research", "intelligence", "recruitment_intelligence.json"),
    os.path.join(WORKSPACE_ROOT, "my-exhibit-platform", "data", "research", "intelligence", "recruitment_intelligence.json"),
]

SEED_ITEMS = [
    {
        "id": "ui-seed-001",
        "companyName": "현대자동차",
        "logoEmoji": "🚗",
        "title": "2026 하반기 ccNC 미래 모빌리티 인포테인먼트 UX/UI 디자이너 (신입)",
        "jobCategory": "연구개발·설계",
        "employmentType": "정규직",
        "careerLevel": "신입",
        "preferredDepartments": ["시각디자인학과", "산업디자인학과", "디자인조형학부", "컴퓨터공학과"],
        "techStacks": ["Figma", "ProtoPie", "HMI", "3D GUI"],
        "deadline": "2026-10-31",
        "originUrl": "https://talent.hyundai.com",
        "sourceUrl": "https://talent.hyundai.com/apply/posting/HMC-2026-UX01",
        "isPartnership": True,
        "location": "서울 서초구 양재본사",
        "matchedDepartment": "시각디자인과",
        "matchedUniversity": "홍익대학교",
        "verificationStatus": "VERIFIED",
        "majorPreferenceStatus": "MAJOR_PREFERENCE_CONFIRMED",
        "evidenceText": "차량용 인포테인먼트(ccNC) 및 인-카 HMI 인터랙션 디자인 실무 역량 보유자 우대 (시각/산업디자인 전공)",
        "sourceId": "src-ui-seed-001",
        "evidenceId": "evi-ui-seed-001",
        "isUiTestSeed": True
    },
    {
        "id": "ui-seed-002",
        "companyName": "네이버 (NAVER)",
        "logoEmoji": "🟢",
        "title": "네이버 플레이스 & 지도 비주얼 인터랙션 디자이너 (신입 공채)",
        "jobCategory": "디자인",
        "employmentType": "정규직",
        "careerLevel": "신입",
        "preferredDepartments": ["시각디자인학과", "산업정보디자인전공", "디지털미디어학과"],
        "techStacks": ["Figma", "GUI", "Design System", "After Effects"],
        "deadline": "2026-10-20",
        "originUrl": "https://recruit.navercorp.com",
        "sourceUrl": "https://recruit.navercorp.com/rcr/view.do?annoId=NAVER-2026-DES01",
        "isPartnership": True,
        "location": "경기 성남시 분당구 1784",
        "matchedDepartment": "시각디자인과",
        "matchedUniversity": "홍익대학교",
        "verificationStatus": "VERIFIED",
        "majorPreferenceStatus": "MAJOR_PREFERENCE_CONFIRMED",
        "evidenceText": "복잡한 공간/장소 데이터를 직관적인 인터페이스로 시각화하는 비주얼 GUI 설계 역량 (시각디자인 우대)",
        "sourceId": "src-ui-seed-002",
        "evidenceId": "evi-ui-seed-002",
        "isUiTestSeed": True
    },
    {
        "id": "ui-seed-003",
        "companyName": "토스 (Toss)",
        "logoEmoji": "💙",
        "title": "2026 프로덕트 디자이너 - 금융 플랫폼 UX/UI (신입)",
        "jobCategory": "디자인",
        "employmentType": "정규직",
        "careerLevel": "신입",
        "preferredDepartments": ["시각디자인학과", "산업정보디자인전공", "디자인조형학부"],
        "techStacks": ["Figma", "UX Research", "Prototyping", "Design System"],
        "deadline": "2026-11-15",
        "originUrl": "https://toss.im/career",
        "sourceUrl": "https://toss.im/career/job-detail?job_id=TOSS-2026-DES01",
        "isPartnership": False,
        "location": "서울 강남구 테헤란로",
        "matchedDepartment": "시각디자인과",
        "matchedUniversity": "홍익대학교",
        "verificationStatus": "VERIFIED",
        "majorPreferenceStatus": "MAJOR_PREFERENCE_CONFIRMED",
        "evidenceText": "누구나 쉽고 명확하게 사용하는 금융 사용자 경험(UX) 가설 검증 및 UI 산출물 프로토타이핑 능력",
        "sourceId": "src-ui-seed-003",
        "evidenceId": "evi-ui-seed-003",
        "isUiTestSeed": True
    },
    {
        "id": "ui-seed-004",
        "companyName": "카카오 (Kakao)",
        "logoEmoji": "🟡",
        "title": "카카오 브랜드 캠페인 및 서비스 마케팅 콘텐츠 기획 (신입)",
        "jobCategory": "마케팅·광고·홍보",
        "employmentType": "정규직",
        "careerLevel": "신입",
        "preferredDepartments": ["광고홍보학과", "경영학과", "미디어커뮤니케이션학과", "시각디자인학과"],
        "techStacks": ["Content Marketing", "Copywriting", "GA4", "Figma"],
        "deadline": "2026-10-25",
        "originUrl": "https://careers.kakao.com",
        "sourceUrl": "https://careers.kakao.com/jobs/KAKAO-2026-MKT01",
        "isPartnership": False,
        "location": "경기 성남시 판교 오피스",
        "matchedDepartment": "미디어커뮤니케이션학과",
        "matchedUniversity": "고려대학교",
        "verificationStatus": "VERIFIED",
        "majorPreferenceStatus": "MAJOR_PREFERENCE_CONFIRMED",
        "evidenceText": "소셜 미디어 캠페인 기획 및 브랜드 비주얼 자산 스토리텔링 제작 실무 역량 우대",
        "sourceId": "src-ui-seed-004",
        "evidenceId": "evi-ui-seed-004",
        "isUiTestSeed": True
    },
    {
        "id": "ui-seed-005",
        "companyName": "LG전자",
        "logoEmoji": "🔴",
        "title": "H&A 스마트 가전 CMF 및 선행 공간 제품 디자이너 (신입)",
        "jobCategory": "연구개발·설계",
        "employmentType": "정규직",
        "careerLevel": "신입",
        "preferredDepartments": ["산업디자인학과", "공업디자인학과", "공간디자인학과", "디자인조형학부"],
        "techStacks": ["Rhino", "Keyshot", "CMF Design", "Photoshop"],
        "deadline": "2026-10-15",
        "originUrl": "https://careers.lg.com",
        "sourceUrl": "https://careers.lg.com/app/job/LGE-2026-HOM01",
        "isPartnership": True,
        "location": "서울 강서구 마곡 LG사이언스파크",
        "matchedDepartment": "산업디자인학과",
        "matchedUniversity": "홍익대학교",
        "verificationStatus": "VERIFIED",
        "majorPreferenceStatus": "MAJOR_PREFERENCE_CONFIRMED",
        "evidenceText": "가전 제품 친환경 신소재 및 공간 조화형 CMF 라이브러리 분석 및 렌더링 역량 (산업/공업디자인 필수)",
        "sourceId": "src-ui-seed-005",
        "evidenceId": "evi-ui-seed-005",
        "isUiTestSeed": True
    },
    {
        "id": "ui-seed-006",
        "companyName": "삼성전자",
        "logoEmoji": "🔷",
        "title": "DX부문 차세대 온디바이스 AI 비주얼 인터페이스 연구원 (신입)",
        "jobCategory": "디자인",
        "employmentType": "정규직",
        "careerLevel": "신입",
        "preferredDepartments": ["디자인학부", "시각디자인", "산업디자인", "컴퓨터공학과"],
        "techStacks": ["Figma", "ProtoPie", "3D Interaction", "AI Prompt UX"],
        "deadline": "2026-09-30",
        "originUrl": "https://www.samsungcareers.com",
        "sourceUrl": "https://www.samsungcareers.com/rec/recruiting/SEC-2026-DX01",
        "isPartnership": False,
        "location": "서울 서초구 우면 R&D 캠퍼스",
        "matchedDepartment": "시각디자인과",
        "matchedUniversity": "서울대학교",
        "verificationStatus": "VERIFIED",
        "majorPreferenceStatus": "MAJOR_PREFERENCE_CONFIRMED",
        "evidenceText": "멀티모달 AI 인터랙션 및 글로벌 스크린 기반 UI/UX 구축 경험자 우대 (디자인 전공 필수)",
        "sourceId": "src-ui-seed-006",
        "evidenceId": "evi-ui-seed-006",
        "isUiTestSeed": True
    },
    {
        "id": "ui-seed-007",
        "companyName": "크래프톤 (KRAFTON)",
        "logoEmoji": "🎮",
        "title": "글로벌 신작 게임 GUI 및 플레이어 온보딩 인터랙션 디자인 (신입)",
        "jobCategory": "디자인",
        "employmentType": "정규직",
        "careerLevel": "신입",
        "preferredDepartments": ["게임디자인학과", "시각디자인학과", "디지털미디어학과"],
        "techStacks": ["Game GUI", "Unreal Engine", "Figma", "Photoshop"],
        "deadline": "2026-11-30",
        "originUrl": "https://krafton.recruiter.co.kr",
        "sourceUrl": "https://krafton.recruiter.co.kr/app/job/KRAFTON-2026-GUI01",
        "isPartnership": False,
        "location": "서울 강남구 역삼동",
        "matchedDepartment": "시각디자인과",
        "matchedUniversity": "홍익대학교",
        "verificationStatus": "VERIFIED",
        "majorPreferenceStatus": "MAJOR_PREFERENCE_CONFIRMED",
        "evidenceText": "게임 엔진 연동 GUI 에셋 제작 및 플레이어 인게임 HUD/온보딩 경험 설계 포트폴리오 우대",
        "sourceId": "src-ui-seed-007",
        "evidenceId": "evi-ui-seed-007",
        "isUiTestSeed": True
    },
    {
        "id": "ui-seed-008",
        "companyName": "CJ ENM",
        "logoEmoji": "🎬",
        "title": "방송 채널 프로모션 비주얼 모션그래픽 디자이너 (신입)",
        "jobCategory": "미디어",
        "employmentType": "정규직",
        "careerLevel": "신입",
        "preferredDepartments": ["영상디자인학과", "시각디자인학과", "애니메이션학과"],
        "techStacks": ["After Effects", "Cinema 4D", "Premiere Pro", "Illustrator"],
        "deadline": "2026-10-31",
        "originUrl": "https://recruit.cjenm.com",
        "sourceUrl": "https://recruit.cjenm.com/job/CJENM-2026-MOT01",
        "isPartnership": False,
        "location": "서울 마포구 상암동",
        "matchedDepartment": "영상디자인학과",
        "matchedUniversity": "국민대학교",
        "verificationStatus": "VERIFIED",
        "majorPreferenceStatus": "MAJOR_PREFERENCE_CONFIRMED",
        "evidenceText": "방송 오프닝 타이틀 및 온에어 프로모션 모션그래픽 포트폴리오 필수 (영상/시각디자인 우대)",
        "sourceId": "src-ui-seed-008",
        "evidenceId": "evi-ui-seed-008",
        "isUiTestSeed": True
    },
    {
        "id": "ui-seed-009",
        "companyName": "쿠팡 (Coupang)",
        "logoEmoji": "🚀",
        "title": "글로벌 로켓배송 풀필먼트 SCM 물류 프로세스 기획 (신입)",
        "jobCategory": "무역·유통",
        "employmentType": "정규직",
        "careerLevel": "신입/경력무관",
        "preferredDepartments": ["물류학과", "국제통상학과", "경영학과", "산업공학과"],
        "techStacks": ["SQL", "Supply Chain", "Data Analysis", "Excel Macro"],
        "deadline": "2026-11-20",
        "originUrl": "https://www.coupang.jobs",
        "sourceUrl": "https://www.coupang.jobs/kr/jobs/CPNG-2026-SCM01",
        "isPartnership": False,
        "location": "서울 송파구 잠실",
        "matchedDepartment": "경영학과",
        "matchedUniversity": "연세대학교",
        "verificationStatus": "VERIFIED",
        "majorPreferenceStatus": "MAJOR_PREFERENCE_CONFIRMED",
        "evidenceText": "풀필먼트 물류 거점 프로세스 최적화 및 물동량 데이터 분석 역량",
        "sourceId": "src-ui-seed-009",
        "evidenceId": "evi-ui-seed-009",
        "isUiTestSeed": True
    },
    {
        "id": "ui-seed-010",
        "companyName": "당근 (Karrot)",
        "logoEmoji": "🥕",
        "title": "동네생활 / 로컬 비즈프로필 B2B 세일즈 & 파트너십 어소시에이트 (신입)",
        "jobCategory": "영업·고객상담",
        "employmentType": "정규직",
        "careerLevel": "신입/경력무관",
        "preferredDepartments": ["경영학과", "경제학과", "미디어커뮤니케이션학부"],
        "techStacks": ["B2B Sales", "Client Relations", "CRM", "Data Tracking"],
        "deadline": "2026-10-31",
        "originUrl": "https://about.daangn.com/jobs",
        "sourceUrl": "https://about.daangn.com/jobs/KARROT-2026-B2B01",
        "isPartnership": False,
        "location": "서울 서초구 교대역",
        "matchedDepartment": "경영학과",
        "matchedUniversity": "서강대학교",
        "verificationStatus": "VERIFIED",
        "majorPreferenceStatus": "MAJOR_PREFERENCE_CONFIRMED",
        "evidenceText": "소상공인 비즈프로필 유치 및 지역 광고 비즈니스 성장 전략 기획",
        "sourceId": "src-ui-seed-010",
        "evidenceId": "evi-ui-seed-010",
        "isUiTestSeed": True
    },
    {
        "id": "ui-seed-011",
        "companyName": "현대건설",
        "logoEmoji": "🏗️",
        "title": "스마트 건축 공간디자인 및 BIM 디지털 트윈 모델링 (신입)",
        "jobCategory": "건설",
        "employmentType": "정규직",
        "careerLevel": "신입",
        "preferredDepartments": ["건축학과", "공간디자인학과", "실내건축디자인학과"],
        "techStacks": ["BIM", "Revit", "AutoCAD", "Rhino"],
        "deadline": "2026-11-10",
        "originUrl": "https://www.hdec.kr/kr/career",
        "sourceUrl": "https://www.hdec.kr/kr/career/posting/HDEC-2026-BIM01",
        "isPartnership": True,
        "location": "서울 종로구 계동사옥",
        "matchedDepartment": "건축학과",
        "matchedUniversity": "한양대학교",
        "verificationStatus": "VERIFIED",
        "majorPreferenceStatus": "MAJOR_PREFERENCE_CONFIRMED",
        "evidenceText": "BIM 기반 3D 디지털 모델링 및 공간 조형 최적화 설계 포트폴리오 (건축/공간디자인 필수)",
        "sourceId": "src-ui-seed-011",
        "evidenceId": "evi-ui-seed-011",
        "isUiTestSeed": True
    },
    {
        "id": "ui-seed-012",
        "companyName": "리인벤션 특허법률사무소",
        "logoEmoji": "⚖️",
        "title": "AI 및 디지털 디자인 지식재산권(IP) 기술가치평가 연구원 (신입)",
        "jobCategory": "전문·특수직",
        "employmentType": "정규직",
        "careerLevel": "신입/경력무관",
        "preferredDepartments": ["디자인학부", "법학과", "기술경영학과", "지식재산학과"],
        "techStacks": ["Patent Analysis", "Design Rights", "Tech Valuation", "IP Strategy"],
        "deadline": "2026-12-31",
        "originUrl": "https://reinvention.co.kr",
        "sourceUrl": "https://reinvention.co.kr/careers/IP-2026-01",
        "isPartnership": True,
        "location": "서울 강남구 역삼동 테헤란로",
        "matchedDepartment": "시각디자인과",
        "matchedUniversity": "홍익대학교",
        "verificationStatus": "VERIFIED",
        "majorPreferenceStatus": "MAJOR_PREFERENCE_CONFIRMED",
        "evidenceText": "디지털 디자인권 및 AI 생성물 특허 분석 역량 (디자인/법학 융합 전공 우대)",
        "sourceId": "src-ui-seed-012",
        "evidenceId": "evi-ui-seed-012",
        "isUiTestSeed": True
    },
    {
        "id": "ui-seed-013",
        "companyName": "토스뱅크 (Toss Bank)",
        "logoEmoji": "🏦",
        "title": "여신/수신 금융 플랫폼 프로덕트 오너(PO) 어시스턴트 (신입)",
        "jobCategory": "금융",
        "employmentType": "정규직",
        "careerLevel": "신입",
        "preferredDepartments": ["경영학과", "금융공학과", "산업정보디자인전공", "컴퓨터공학과"],
        "techStacks": ["Fintech Product", "SQL", "Figma", "Data Analysis"],
        "deadline": "2026-11-20",
        "originUrl": "https://tossbank.career",
        "sourceUrl": "https://tossbank.career/job-detail?job_id=TBANK-2026-PO01",
        "isPartnership": False,
        "location": "서울 강남구 테헤란로",
        "matchedDepartment": "경영학과",
        "matchedUniversity": "서울대학교",
        "verificationStatus": "VERIFIED",
        "majorPreferenceStatus": "MAJOR_PREFERENCE_CONFIRMED",
        "evidenceText": "데이터 기반 핀테크 서비스 가설 설정 및 사용자 여정 개선 역량 (경영/디자인/공학 전공)",
        "sourceId": "src-ui-seed-013",
        "evidenceId": "evi-ui-seed-013",
        "isUiTestSeed": True
    },
    {
        "id": "ui-seed-014",
        "companyName": "네이버웹툰",
        "logoEmoji": "📗",
        "title": "글로벌 웹툰/웹소설 콘텐츠 인터랙션 UI 디자이너 (신입)",
        "jobCategory": "디자인",
        "employmentType": "정규직",
        "careerLevel": "신입",
        "preferredDepartments": ["시각디자인학과", "애니메이션학과", "디지털미디어학과"],
        "techStacks": ["Figma", "Photoshop", "Interaction Design", "Prototyping"],
        "deadline": "2026-11-10",
        "originUrl": "https://webtoonscorp.com/careers",
        "sourceUrl": "https://webtoonscorp.com/careers/posting/WEBTOON-2026-UI01",
        "isPartnership": False,
        "location": "경기 성남시 분당구 판교역",
        "matchedDepartment": "시각디자인과",
        "matchedUniversity": "홍익대학교",
        "verificationStatus": "VERIFIED",
        "majorPreferenceStatus": "MAJOR_PREFERENCE_CONFIRMED",
        "evidenceText": "글로벌 모바일 독자 경험을 위한 뷰어 UI 및 마이크로 인터랙션 제작 역량 (시각/디지털미디어 우대)",
        "sourceId": "src-ui-seed-014",
        "evidenceId": "evi-ui-seed-014",
        "isUiTestSeed": True
    },
    {
        "id": "ui-seed-015",
        "companyName": "현대모비스",
        "logoEmoji": "🚘",
        "title": "차세대 자율주행 모빌리티 PBV CMF 및 인터랙션 디자이너 (신입)",
        "jobCategory": "연구개발·설계",
        "employmentType": "정규직",
        "careerLevel": "신입",
        "preferredDepartments": ["산업디자인학과", "시각디자인학과", "공간디자인학과"],
        "techStacks": ["CMF Design", "Rhino", "KeyShot", "ProtoPie"],
        "deadline": "2026-11-25",
        "originUrl": "https://mobis.recruiter.co.kr",
        "sourceUrl": "https://mobis.recruiter.co.kr/app/job/MOBIS-2026-CMF01",
        "isPartnership": True,
        "location": "경기 용인시 마북 기술연구소",
        "matchedDepartment": "산업디자인학과",
        "matchedUniversity": "홍익대학교",
        "verificationStatus": "VERIFIED",
        "majorPreferenceStatus": "MAJOR_PREFERENCE_CONFIRMED",
        "evidenceText": "모빌리티 내장 소재 감성 품질 분석 및 인터랙티브 조명/디스플레이 CMF 설계",
        "sourceId": "src-ui-seed-015",
        "evidenceId": "evi-ui-seed-015",
        "isUiTestSeed": True
    }
]

def populate():
    # Compute content hashes
    for item in SEED_ITEMS:
        raw_sig = f"{item['companyName']}_{item['title']}_{item['deadline']}_{item['evidenceText']}"
        item["contentHash"] = hashlib.sha256(raw_sig.encode("utf-8")).hexdigest()

    payload = {
        "updated_at": datetime.now().isoformat(),
        "type": "UI_TEST_SEED_DATASET",
        "total_discovered": len(SEED_ITEMS),
        "total_verified": len(SEED_ITEMS),
        "unverified_count": 0,
        "stale_count": 0,
        "conflicted_count": 0,
        "verified_postings": SEED_ITEMS
    }

    for p in INTEL_PATHS:
        os.makedirs(os.path.dirname(p), exist_ok=True)
        with open(p, "w", encoding="utf-8") as f:
            json.dump(payload, f, ensure_ascii=False, indent=2)
        print(f"Populated {len(SEED_ITEMS)} UI test/seed items to {p}")

if __name__ == "__main__":
    populate()
