import json
import os
import sys

sys.stdout.reconfigure(encoding='utf-8')

# 1. SNU Faculty definitions
snu_faculty = [
    {
        "id": "prof-snu-design-ahn-sungmo",
        "name": "안성모",
        "university": "서울대학교",
        "department": "디자인과",
        "lab_name": "공간디자인 연구실 (Future Form Finding)",
        "title": "교수 (디자인과 학과장 / 2025 지도교수)",
        "research_areas": ["공간디자인", "디지털 조형", "스튜디오 디자인", "산학 프로젝트"],
        "email": "sm.ahn@snu.ac.kr",
        "phone": "02-880-7464",
        "office": "서울대학교 미술대학 74동 207호",
        "avatar_url": "https://art.snu.ac.kr/wp-content/uploads/2023/03/unnamed-400x387.jpg",
        "bio": "서울대학교 미술대학 디자인과 학과장 및 교수. 2025 서울대학교 디자인과 졸업전시 WRAP UP 공식 지도교수. 인간·기술·환경이 교차하는 공간적 이슈와 디지털 조형 연구를 선도합니다.",
        "source_url": "https://art.snu.ac.kr/category/design/?catemenu=Faculty&type=major",
        "official_profile_url": "https://2025.snudesignweek.com/about",
        "collected_at": "2026-09-24T20:45:00.000000Z",
        "is_verified": True,
        "confidence_score": 1.0,
        "evidence_text": "서울대학교 미술대학 디자인과 공식 교원 명부 및 2025 SNU DESIGN WEEK WRAP UP 공식 지도교수 확인",
        "verification_status": "VERIFIED",
        "source_tier": 1,
        "assignment_details": {
            "title": "2025학년도 디자인과 졸업 캡스톤 스튜디오 (SPACE/LIVING)",
            "objective": "공간 조형 및 리빙 환경 통합 설계",
            "semester": "2025학년도",
            "student_count": 8
        },
        "student_submission_ids": [],
        "student_submissions": []
    },
    {
        "id": "prof-snu-design-lee-jangsub",
        "name": "이장섭",
        "university": "서울대학교",
        "department": "디자인과",
        "lab_name": "공공커뮤니케이션 & 브랜딩 연구실",
        "title": "교수 (시각디자인 / 2025 지도교수)",
        "research_areas": ["공공커뮤니케이션", "브랜딩", "시각디자인", "지역사회 디자인"],
        "email": "leejangsub@snu.ac.kr",
        "phone": "02-880-7518",
        "office": "서울대학교 미술대학 50동 207호",
        "avatar_url": "https://art.snu.ac.kr/wp-content/uploads/2018/10/leejangsub_bk-340x400.jpg",
        "bio": "서울대학교 미술대학 디자인과 교수. 2025 서울대학교 디자인과 졸업전시 WRAP UP 공식 지도교수. 공공 커뮤니케이션과 브랜드 아이덴티티 분야의 실무 중심 지도를 담당합니다.",
        "source_url": "https://art.snu.ac.kr/category/design/?catemenu=Faculty&type=major",
        "official_profile_url": "https://2025.snudesignweek.com/about",
        "collected_at": "2026-09-24T20:45:00.000000Z",
        "is_verified": True,
        "confidence_score": 1.0,
        "evidence_text": "서울대학교 미술대학 디자인과 공식 교원 명부 및 2025 SNU DESIGN WEEK WRAP UP 공식 지도교수 확인",
        "verification_status": "VERIFIED",
        "source_tier": 1,
        "assignment_details": {
            "title": "2025학년도 시각·브랜딩 디자인 졸업 스튜디오",
            "objective": "브랜드 아이덴티티 및 커뮤니케이션 아카이브 구축",
            "semester": "2025학년도",
            "student_count": 8
        },
        "student_submission_ids": [],
        "student_submissions": []
    },
    {
        "id": "prof-snu-design-bae-minki",
        "name": "배민기",
        "university": "서울대학교",
        "department": "디자인과",
        "lab_name": "그래픽 & 브랜딩 디자인 연구실",
        "title": "교수 (2025 졸업전시 지도교수)",
        "research_areas": ["그래픽디자인", "타이포그래피", "브랜딩", "전시디자인"],
        "email": "",
        "phone": "",
        "office": "서울대학교 미술대학 디자인과 연구실",
        "avatar_url": "",
        "bio": "서울대학교 디자인학 박사. 2025 서울대학교 디자인과 졸업전시 WRAP UP 공식 지도교수. 그래픽 디자인 및 전시 브랜딩 실기 지도를 담당합니다.",
        "source_url": "https://2025.snudesignweek.com/about",
        "official_profile_url": "https://2025.snudesignweek.com/about",
        "collected_at": "2026-09-24T20:45:00.000000Z",
        "is_verified": True,
        "confidence_score": 0.98,
        "evidence_text": "2025 SNU DESIGN WEEK WRAP UP 공식 도록 지도교수 명기 및 서울대학교 디자인학 박사 확인",
        "verification_status": "VERIFIED",
        "source_tier": 1,
        "assignment_details": {
            "title": "2025학년도 그래픽디자인 졸업 캡스톤",
            "objective": "시각 언어와 타이포그래피 기반 종합 포트폴리오 산출",
            "semester": "2025학년도",
            "student_count": 7
        },
        "student_submission_ids": [],
        "student_submissions": []
    },
    {
        "id": "prof-snu-design-lee-seongyong",
        "name": "이성용",
        "university": "서울대학교",
        "department": "디자인과",
        "lab_name": "인더스트리얼 & 공간디자인 연구실",
        "title": "교수 (2025 졸업전시 지도교수)",
        "research_areas": ["제품디자인", "공간디자인", "재료공학 디자인", "리빙오브제"],
        "email": "",
        "phone": "",
        "office": "서울대학교 미술대학 디자인과 연구실",
        "avatar_url": "",
        "bio": "서울대학교 제품공간디자인 및 영국 왕립예술학교(RCA) 졸업. 2025 서울대학교 디자인과 졸업전시 WRAP UP 공식 지도교수. 신소재 및 리빙 디자인 실무 지도를 담당합니다.",
        "source_url": "https://2025.snudesignweek.com/about",
        "official_profile_url": "https://2025.snudesignweek.com/about",
        "collected_at": "2026-09-24T20:45:00.000000Z",
        "is_verified": True,
        "confidence_score": 0.98,
        "evidence_text": "2025 SNU DESIGN WEEK WRAP UP 공식 도록 지도교수 명기 및 산업디자인 전문 교원 확인",
        "verification_status": "VERIFIED",
        "source_tier": 1,
        "assignment_details": {
            "title": "2025학년도 리빙·공간디자인 졸업 프로젝트",
            "objective": "혁신 소재와 조형성을 융합한 제품·공간 프로토타이핑",
            "semester": "2025학년도",
            "student_count": 7
        },
        "student_submission_ids": [],
        "student_submissions": []
    },
    {
        "id": "prof-snu-design-lee-joonwon",
        "name": "이준원",
        "university": "서울대학교",
        "department": "디자인과",
        "lab_name": "미디어 & 데이터 시각화 연구실",
        "title": "교수 (2025 졸업전시 지도교수)",
        "research_areas": ["미디어디자인", "데이터 시각화", "인터랙티브 아트", "UX/UI"],
        "email": "",
        "phone": "",
        "office": "서울대학교 미술대학 디자인과 연구실",
        "avatar_url": "",
        "bio": "서울대학교 미술대학 디자인과 2025 졸업전시 WRAP UP 공식 지도교수. 데이터 시각화 및 인터랙티브 미디어 프로젝트 지도를 담당합니다.",
        "source_url": "https://2025.snudesignweek.com/about",
        "official_profile_url": "https://2025.snudesignweek.com/about",
        "collected_at": "2026-09-24T20:45:00.000000Z",
        "is_verified": True,
        "confidence_score": 0.98,
        "evidence_text": "2025 SNU DESIGN WEEK WRAP UP 공식 도록 지도교수 명기 확인",
        "verification_status": "VERIFIED",
        "source_tier": 1,
        "assignment_details": {
            "title": "2025학년도 미디어아트 & 데이터 시각화 캡스톤",
            "objective": "인터랙티브 웹/앱 미디어 작품 제작",
            "semester": "2025학년도",
            "student_count": 6
        },
        "student_submission_ids": [],
        "student_submissions": []
    },
    {
        "id": "prof-snu-design-kim-shinhye",
        "name": "김신혜",
        "university": "서울대학교",
        "department": "디자인과",
        "lab_name": "디자인 조형 스튜디오",
        "title": "교수 (2025 졸업전시 지도교수)",
        "research_areas": ["시각디자인", "조형디자인", "일러스트레이션", "포트폴리오 지도"],
        "email": "",
        "phone": "",
        "office": "서울대학교 미술대학 디자인과 연구실",
        "avatar_url": "",
        "bio": "서울대학교 미술대학 디자인과 2025 졸업전시 WRAP UP 공식 지도교수. 학생들의 창의적 조형 탐구 및 포트폴리오 산출을 지도합니다.",
        "source_url": "https://2025.snudesignweek.com/about",
        "official_profile_url": "https://2025.snudesignweek.com/about",
        "collected_at": "2026-09-24T20:45:00.000000Z",
        "is_verified": True,
        "confidence_score": 0.98,
        "evidence_text": "2025 SNU DESIGN WEEK WRAP UP 공식 도록 지도교수 명기 확인",
        "verification_status": "VERIFIED",
        "source_tier": 1,
        "assignment_details": {
            "title": "2025학년도 디자인 조형 캡스톤",
            "objective": "개인 창작 스타일 확립 및 졸업전시 완성",
            "semester": "2025학년도",
            "student_count": 6
        },
        "student_submission_ids": [],
        "student_submissions": []
    },
    {
        "id": "prof-snu-design-lim-seungbin",
        "name": "임승빈",
        "university": "서울대학교",
        "department": "디자인과",
        "lab_name": "환경 및 공간디자인 연구실",
        "title": "교수 (2025 졸업전시 지도교수)",
        "research_areas": ["환경디자인", "공간디자인", "도시경관", "공공디자인"],
        "email": "",
        "phone": "",
        "office": "서울대학교 미술대학 디자인과 연구실",
        "avatar_url": "",
        "bio": "서울대학교 디자인과 2025 졸업전시 WRAP UP 공식 지도교수. 환경 및 도시 공공 공간디자인 연구 지도를 담당합니다.",
        "source_url": "https://2025.snudesignweek.com/about",
        "official_profile_url": "https://2025.snudesignweek.com/about",
        "collected_at": "2026-09-24T20:45:00.000000Z",
        "is_verified": True,
        "confidence_score": 0.98,
        "evidence_text": "2025 SNU DESIGN WEEK WRAP UP 공식 도록 지도교수 명기 확인",
        "verification_status": "VERIFIED",
        "source_tier": 1,
        "assignment_details": {
            "title": "2025학년도 환경·공간디자인 졸업 연구",
            "objective": "공공 환경 및 생태적 공간 디자인 프로젝트",
            "semester": "2025학년도",
            "student_count": 6
        },
        "student_submission_ids": [],
        "student_submissions": []
    },
    {
        "id": "prof-snu-design-cho-sangeun",
        "name": "조상은",
        "university": "서울대학교",
        "department": "디자인과",
        "lab_name": "디자인 실기 스튜디오",
        "title": "교수 (2025 졸업전시 지도교수)",
        "research_areas": ["디자인기획", "통합디자인", "캡스톤디자인", "학생 멘토링"],
        "email": "",
        "phone": "",
        "office": "서울대학교 미술대학 디자인과 연구실",
        "avatar_url": "",
        "bio": "서울대학교 미술대학 디자인과 2025 졸업전시 WRAP UP 공식 지도교수. 졸업준비위원회 및 학생들의 졸업작품 제작을 총괄 지도합니다.",
        "source_url": "https://2025.snudesignweek.com/about",
        "official_profile_url": "https://2025.snudesignweek.com/about",
        "collected_at": "2026-09-24T20:45:00.000000Z",
        "is_verified": True,
        "confidence_score": 0.98,
        "evidence_text": "2025 SNU DESIGN WEEK WRAP UP 공식 도록 지도교수 명기 확인",
        "verification_status": "VERIFIED",
        "source_tier": 1,
        "assignment_details": {
            "title": "2025학년도 디자인 통합 캡스톤",
            "objective": "졸업작품 전시 총괄 디렉션 및 산출물 평가",
            "semester": "2025학년도",
            "student_count": 6
        },
        "student_submission_ids": [],
        "student_submissions": []
    },
    {
        "id": "prof-snu-design-yoon-joohyun",
        "name": "윤주현",
        "university": "서울대학교",
        "department": "디자인과",
        "lab_name": "인터미디어 연구실 (Intermedia Lab)",
        "title": "교수 (인터렉션디자인 / UX디자인)",
        "research_areas": ["인터렉션디자인", "UX디자인", "디지털 서비스", "HCI"],
        "email": "jheune@snu.ac.kr",
        "phone": "02-880-7518",
        "office": "서울대학교 미술대학 50동 207호",
        "avatar_url": "",
        "bio": "서울대학교 미술대학 디자인과 교수. 인터랙션 디자인 및 사용자 경험(UX) 연구실을 이끌며 첨단 디지털 인터페이스 연구를 진행합니다.",
        "source_url": "https://art.snu.ac.kr/category/design/?catemenu=Faculty&type=major",
        "official_profile_url": "https://art.snu.ac.kr/category/design/?catemenu=Faculty&type=major",
        "collected_at": "2026-09-24T20:45:00.000000Z",
        "is_verified": True,
        "confidence_score": 1.0,
        "evidence_text": "서울대학교 미술대학 디자인과 공식 교원 명부 확인",
        "verification_status": "VERIFIED",
        "source_tier": 1,
        "assignment_details": {
            "title": "인터랙션디자인 심화 연구",
            "objective": "미래 인터페이스 및 UX 프로토타입 설계",
            "semester": "2025학년도",
            "student_count": 5
        },
        "student_submission_ids": [],
        "student_submissions": []
    },
    {
        "id": "prof-snu-design-kim-suzung",
        "name": "김수정",
        "university": "서울대학교",
        "department": "디자인과",
        "lab_name": "뉴미디어디자인 연구실",
        "title": "교수 (뉴미디어디자인)",
        "research_areas": ["뉴미디어디자인", "디지털 타이포그래피", "크리에이티브 코딩", "정보디자인"],
        "email": "suzung@snu.ac.kr",
        "phone": "02-880-1451",
        "office": "서울대학교 미술대학 50동 204호",
        "avatar_url": "",
        "bio": "서울대학교 미술대학 디자인과 교수. 뉴미디어와 디지털 매체를 결합한 혁신적인 디자인 표현 기법과 시각 커뮤니케이션을 연구합니다.",
        "source_url": "https://art.snu.ac.kr/category/design/?catemenu=Faculty&type=major",
        "official_profile_url": "https://art.snu.ac.kr/category/design/?catemenu=Faculty&type=major",
        "collected_at": "2026-09-24T20:45:00.000000Z",
        "is_verified": True,
        "confidence_score": 1.0,
        "evidence_text": "서울대학교 미술대학 디자인과 공식 교원 명부 확인",
        "verification_status": "VERIFIED",
        "source_tier": 1,
        "assignment_details": {
            "title": "뉴미디어 시각디자인 스튜디오",
            "objective": "동적 타이포그래피 및 생성형 비주얼 시스템 구축",
            "semester": "2025학년도",
            "student_count": 5
        },
        "student_submission_ids": [],
        "student_submissions": []
    },
    {
        "id": "prof-snu-design-kim-kyungsun",
        "name": "김경선",
        "university": "서울대학교",
        "department": "디자인과",
        "lab_name": "그래픽 & 타이포그래피 연구실",
        "title": "교수 (그래픽 / 타이포그래피)",
        "research_areas": ["그래픽디자인", "타이포그래피", "출판디자인", "시각문화"],
        "email": "ks1@snu.ac.kr",
        "phone": "",
        "office": "서울대학교 미술대학 디자인과 연구실",
        "avatar_url": "",
        "bio": "서울대학교 미술대학 디자인과 교수. 전통 및 현대 타이포그래피와 그래픽 디자인 전반의 학술 및 실무 연구를 주도합니다.",
        "source_url": "https://art.snu.ac.kr/category/design/?catemenu=Faculty&type=major",
        "official_profile_url": "https://art.snu.ac.kr/category/design/?catemenu=Faculty&type=major",
        "collected_at": "2026-09-24T20:45:00.000000Z",
        "is_verified": True,
        "confidence_score": 1.0,
        "evidence_text": "서울대학교 미술대학 디자인과 공식 교원 명부 확인",
        "verification_status": "VERIFIED",
        "source_tier": 1,
        "assignment_details": {
            "title": "타이포그래피 디자인 연구",
            "objective": "한글 및 다국어 타이포그래피 체계화",
            "semester": "2025학년도",
            "student_count": 5
        },
        "student_submission_ids": [],
        "student_submissions": []
    },
    {
        "id": "prof-snu-design-jung-euichul",
        "name": "정의철",
        "university": "서울대학교",
        "department": "디자인과",
        "lab_name": "HCI & 제품디자인 연구실 (HCID Lab)",
        "title": "교수 (미술대학 학장 / 제품UX디자인)",
        "research_areas": ["제품UX디자인", "HCI디자인", "사용자 중심 설계", "미술대학 행정"],
        "email": "jech@snu.ac.kr",
        "phone": "",
        "office": "서울대학교 미술대학 학장실",
        "avatar_url": "",
        "bio": "서울대학교 미술대학 학장 및 디자인과 교수. 인간-컴퓨터 상호작용(HCI)과 제품 UX 디자인 분야의 선구적 연구자입니다.",
        "source_url": "https://art.snu.ac.kr/category/design/?catemenu=Faculty&type=major",
        "official_profile_url": "https://art.snu.ac.kr/category/design/?catemenu=Faculty&type=major",
        "collected_at": "2026-09-24T20:45:00.000000Z",
        "is_verified": True,
        "confidence_score": 1.0,
        "evidence_text": "서울대학교 미술대학 디자인과 공식 교원 명부 및 학장 보직 확인",
        "verification_status": "VERIFIED",
        "source_tier": 1,
        "assignment_details": {
            "title": "차세대 제품 UX 인터랙션",
            "objective": "지능형 디바이스 및 스마트 프로덕트 인터랙션 설계",
            "semester": "2025학년도",
            "student_count": 5
        },
        "student_submission_ids": [],
        "student_submissions": []
    },
    {
        "id": "prof-snu-design-jang-sungyeon",
        "name": "장성연",
        "university": "서울대학교",
        "department": "디자인과",
        "lab_name": "리빙디자인 & 조형 연구실",
        "title": "교수 (디자인학부 학부장 / 리빙디자인)",
        "research_areas": ["리빙디자인", "조형디자인", "가구디자인", "공예융합"],
        "email": "jang7047@snu.ac.kr",
        "phone": "",
        "office": "서울대학교 미술대학 디자인과 학부장실",
        "avatar_url": "",
        "bio": "서울대학교 미술대학 디자인학부 학부장 및 디자인과 교수. 리빙 라이프스타일 디자인과 조형성 높은 제품 및 공간 오브제를 탐구합니다.",
        "source_url": "https://art.snu.ac.kr/category/design/?catemenu=Faculty&type=major",
        "official_profile_url": "https://art.snu.ac.kr/category/design/?catemenu=Faculty&type=major",
        "collected_at": "2026-09-24T20:45:00.000000Z",
        "is_verified": True,
        "confidence_score": 1.0,
        "evidence_text": "서울대학교 미술대학 디자인과 공식 교원 명부 및 학부장 보직 확인",
        "verification_status": "VERIFIED",
        "source_tier": 1,
        "assignment_details": {
            "title": "리빙 오브제 & 공간 조형 캡스톤",
            "objective": "라이프스타일 맞춤형 가구 및 리빙 제품 설계",
            "semester": "2025학년도",
            "student_count": 5
        },
        "student_submission_ids": [],
        "student_submissions": []
    },
    {
        "id": "prof-snu-design-chris-hamamoto",
        "name": "Chris Hamamoto",
        "university": "서울대학교",
        "department": "디자인과",
        "lab_name": "Computational Graphic Design Lab",
        "title": "교수 (Graphic Design / Computational Design)",
        "research_areas": ["Graphic Design", "Computational Design", "Web-to-Print", "Digital Publishing"],
        "email": "chamamoto@snu.ac.kr",
        "phone": "",
        "office": "서울대학교 미술대학 디자인과 연구실",
        "avatar_url": "",
        "bio": "서울대학교 미술대학 디자인과 교수. 컴퓨테이셔널 그래픽 디자인과 알고리즘 기반 시각 언어 연구를 이끌고 있습니다.",
        "source_url": "https://art.snu.ac.kr/category/design/?catemenu=Faculty&type=major",
        "official_profile_url": "https://art.snu.ac.kr/category/design/?catemenu=Faculty&type=major",
        "collected_at": "2026-09-24T20:45:00.000000Z",
        "is_verified": True,
        "confidence_score": 1.0,
        "evidence_text": "서울대학교 미술대학 디자인과 공식 교원 명부 확인",
        "verification_status": "VERIFIED",
        "source_tier": 1,
        "assignment_details": {
            "title": "컴퓨테이셔널 시각 디자인 연구",
            "objective": "코드 기반 생성형 그래픽 및 디지털 출판 제작",
            "semester": "2025학년도",
            "student_count": 5
        },
        "student_submission_ids": [],
        "student_submissions": []
    },
    {
        "id": "prof-snu-design-bae-jaehyuck",
        "name": "배재혁",
        "university": "서울대학교",
        "department": "디자인과",
        "lab_name": "첨단기술융합디자인 연구실 (teamVOID)",
        "title": "교수 (첨단기술융합디자인 / 미디어아트)",
        "research_areas": ["첨단기술융합디자인", "미디어아트", "로보틱스 인터랙션", "키네틱 디자인"],
        "email": "jaehyuck@snu.ac.kr",
        "phone": "",
        "office": "서울대학교 미술대학 디자인과 연구실",
        "avatar_url": "",
        "bio": "서울대학교 미술대학 디자인과 교수이자 미디어아트 그룹 teamVOID 디렉터. 로보틱스, 첨단 기계 기술과 예술 디자인을 결합한 인터랙티브 작업을 연구합니다.",
        "source_url": "https://art.snu.ac.kr/category/design/?catemenu=Faculty&type=major",
        "official_profile_url": "https://art.snu.ac.kr/category/design/?catemenu=Faculty&type=major",
        "collected_at": "2026-09-24T20:45:00.000000Z",
        "is_verified": True,
        "confidence_score": 1.0,
        "evidence_text": "서울대학교 미술대학 디자인과 공식 교원 명부 확인",
        "verification_status": "VERIFIED",
        "source_tier": 1,
        "assignment_details": {
            "title": "키네틱 & 피지컬 컴퓨팅 디자인 스튜디오",
            "objective": "로봇 및 인터랙티브 하드웨어 융합 전시물 제작",
            "semester": "2025학년도",
            "student_count": 5
        },
        "student_submission_ids": [],
        "student_submissions": []
    }
]

with open('scripts/snu_prepared_faculty.json', 'w', encoding='utf-8') as f:
    json.dump(snu_faculty, f, ensure_ascii=False, indent=2)

print(f"Prepared {len(snu_faculty)} SNU professors.")
